//long descriptions
var Info = {
	ambTemp:"Ambient Temp (ºC)",
	amount:"Number",
	area:"Area (m2)",
	avgRate:"Average rate (min/use)",
	cap:"Capacity (L/load)",
	dewPoin:"Dew point (ºC)",
	diners:"Number of diners", 
	discRate:"Discharge rate (L/min)",
	duration:"Duration (min)",
	flushCap:"Flush capacity (L/flush)",
	freq:"Uses/person/day",
	guests:"Number of guests",
	irrigationRate:"Irrigation rate (L/min)",
	loadpday:"Load per day (kg/day)",
	loadsPdiner:"Loads per diner",
	loadsPerGuest:"Loads per guest",
	perc:"% Volume sinks filled",
	speed:"Speed (L/min)",
	tubVol:"Bathtub volume (m3)",
	useDuration:"Use duration (min/use/person)",
	useFreq:"Use frequency (uses/day)",
	vol:"Total volume (m3)",
	watCons:"Water consumption (L/person/day)",
	watTemp:"Water Temp (ºC)",
	windVel:"Wind Velocity (m/s)",
}
